#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

def sort(string):
    dic = Counter(string)
    tup = sorted(dic.items(), key = lambda x: (-x[1],x[0]))[:3]
    return(tup)

if __name__ == '__main__':
    s = input()
    tup = sort(s)
    for i, c in tup:
        print(i, c)
